#!/usr/bin/env node
/**
 * Cursor hook: sessionStart — license gate, telemetry flush, and optional
 * orchestration session init. Everything here is best-effort and silent on
 * success: an offline machine, a broken server, or missing files must never
 * break the session (the hook always exits 0).
 *
 * LICENSE GATE (warn-7 / disable-14 / instant-restore): this standalone script
 * cannot import the CLI package, so it MIRRORS the pure decision logic in
 * packages/cli/src/license-gate.ts — keep thresholds and decisions in sync
 * (24h revalidation window; explicit KEY_INVALID/KEY_EXPIRED enforces now;
 * otherwise offline grace: <7d silent, 7-13d warn, >=14d enforce).
 *
 * TELEMETRY TRANSPORT IS SHARED with packages/cli/src/flush-journal.ts and
 * packages/orchestrator/src/state-machine.ts: the v2 claim journal
 * (~/.enterprise-skills/.telemetry-journal.jsonl, one JSON object per line,
 * CROSS_PROCESS_FLUSH_DESIGN §3.2). This flusher MIRRORS flush-journal.ts the
 * same way the license gate mirrors license-gate.ts: flushers serialize on an
 * exclusive-create LOCK file (rename is NOT an exclusivity primitive on
 * Windows — ES-P0-JOURNAL-WINDOWS-EXACTLY-ONCE), the journal is claimed by
 * rename ONLY under that lock, POST in batches of 50, append what could not
 * cross BACK to the live journal (never overwrite — D-3), sweep orphaned
 * claims older than 15 minutes only when their owner process is gone (or the
 * hard pid-recycling bound passes), and drain a v1 array file left by old
 * writers (D-4). The 200 cap is enforced here at claim time (§3.3). A claim
 * whose restore fails is LEFT for the sweep, never unlinked.
 */
import {
  readFileSync,
  writeFileSync,
  existsSync,
  appendFileSync,
  mkdirSync,
  readdirSync,
  renameSync,
  rmdirSync,
  rmSync,
  cpSync,
  statSync,
} from 'fs';
import { spawnSync } from 'child_process';
import { join, dirname } from 'path';
import { hostname } from 'os';
import { createHash, randomUUID } from 'crypto';

const cwd = process.cwd();
const configPath = join(cwd, '.project-ai', 'orchestration-hooks.json');
const sessionPath = join(cwd, '.project-ai', 'skill-outputs', '_session-context.yaml');

const HOME_DIR = process.env.USERPROFILE ?? process.env.HOME ?? '';
const ES_DIR = join(HOME_DIR, '.enterprise-skills');
const LICENSE_FILE = join(ES_DIR, 'license.json');
const QUEUE_FILE = join(ES_DIR, '.telemetry-queue.json'); // v1 — drained into the journal, never rewritten (D-4)
const JOURNAL_FILE = join(ES_DIR, '.telemetry-journal.jsonl');
const DISABLED_ROOT = join(ES_DIR, '.disabled-skills');
// Universal update-notification surface (ADR 0001): the cache written by
// `enterprise-skills update check`. Read-only + offline here — no network call,
// so it never blocks or slows session start.
const UPDATE_CACHE_FILE = join(ES_DIR, '.update-cache.json');

// Same override + production hosts the CLI uses: validate-key lives on
// enterpriseskills.ai (core/src/license.ts VALIDATION_API), telemetry on
// enterprise-skills-site.vercel.app (cli/src/telemetry.ts API_BASE).
const API_OVERRIDE = process.env.ENTERPRISE_SKILLS_API_BASE
  ? process.env.ENTERPRISE_SKILLS_API_BASE.replace(/\/$/, '')
  : null;
const VALIDATE_URL = `${API_OVERRIDE ?? 'https://enterpriseskills.ai'}/api/validate-key`;
const TELEMETRY_URL = `${API_OVERRIDE ?? 'https://enterprise-skills-site.vercel.app'}/api/telemetry`;

// Thresholds — mirror packages/cli/src/license-gate.ts.
const REVALIDATE_AFTER_HOURS = 24;
const WARN_AFTER_DAYS = 7;
const ENFORCE_AFTER_DAYS = 14;

function log(msg) {
  try {
    const dir = join(cwd, '.project-ai', 'hook-logs');
    mkdirSync(dir, { recursive: true });
    appendFileSync(join(dir, 'session-start.log'), `[${new Date().toISOString()}] ${msg}\n`);
  } catch {
    /* ignore */
  }
}

function drainStdin() {
  try {
    if (!process.stdin.isTTY) {
      readFileSync(0, 'utf8');
    }
  } catch {
    /* ignore */
  }
}

function readJson(file) {
  try {
    return JSON.parse(readFileSync(file, 'utf8'));
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// License gate (warn-7 / disable-14 / instant-restore)
// ---------------------------------------------------------------------------

function projectHash() {
  return createHash('sha256').update(cwd).digest('hex').slice(0, 16);
}

function quarantineDir() {
  return join(DISABLED_ROOT, projectHash());
}

function markerFile() {
  return join(quarantineDir(), 'marker.json');
}

/**
 * Skill ids the tool itself installed: read from the global bundle manifest
 * (~/.enterprise-skills/registry/canonical-skills.yaml — written by
 * installBundle in cli/src/content.ts). Regex-parsed to stay dependency-free;
 * the file is generated by js-yaml so `skill_id: <id>` lines are stable.
 * Empty set (no manifest / unreadable) means we cannot tell what is
 * tool-installed, so the gate enforces NOTHING — when in doubt, leave it.
 */
function installedSkillIds() {
  const ids = new Set();
  try {
    const manifest = readFileSync(join(ES_DIR, 'registry', 'canonical-skills.yaml'), 'utf8');
    for (const m of manifest.matchAll(/^\s*-?\s*skill_id:\s*['"]?([A-Za-z0-9._-]+)['"]?\s*$/gm)) {
      ids.add(m[1]);
    }
  } catch {
    /* no global manifest — nothing is provably tool-installed */
  }
  return ids;
}

/** Move (never delete). rename first; cross-device falls back to copy+remove-source. */
function moveEntry(from, to) {
  mkdirSync(dirname(to), { recursive: true });
  try {
    renameSync(from, to);
  } catch {
    cpSync(from, to, { recursive: true });
    rmSync(from, { recursive: true });
  }
}

/**
 * ENFORCE: de-render by MOVING tool-installed skill renders into quarantine.
 * Scope is surgically limited to `<project>/.cursor/skills/<skill_id>/`
 * directories that (a) match a skill id from the global bundle manifest and
 * (b) have the exact shape the cursor adapter renders (a directory containing
 * SKILL.md — see packages/adapters/src/adapters/cursor.ts). Customer code,
 * hand-written skills, and any other .cursor files are never touched.
 */
function enforceLicenseGate() {
  try {
    const ids = installedSkillIds();
    if (ids.size === 0) {
      log('license gate: no global skill manifest — nothing enforced');
      return;
    }
    const skillsDir = join(cwd, '.cursor', 'skills');
    if (!existsSync(skillsDir)) return;

    const moved = [];
    for (const entry of readdirSync(skillsDir)) {
      if (!ids.has(entry)) continue; // not tool-installed -> leave it
      const from = join(skillsDir, entry);
      try {
        if (!statSync(from).isDirectory() || !existsSync(join(from, 'SKILL.md'))) continue;
      } catch {
        continue;
      }
      const to = join(quarantineDir(), 'skills', entry);
      try {
        moveEntry(from, to);
        moved.push({ from, to });
      } catch (e) {
        log(`license gate: could not quarantine ${from}: ${e}`);
      }
    }
    if (moved.length === 0) return; // already enforced (or nothing rendered) -> stay silent

    const existing = readJson(markerFile());
    const entries = Array.isArray(existing?.entries) ? existing.entries.concat(moved) : moved;
    writeFileSync(
      markerFile(),
      `${JSON.stringify({ project_path: cwd, disabled_at: new Date().toISOString(), entries }, null, 2)}\n`,
    );
    console.log(
      'Enterprise Skills license could not be verified — skills paused. Run: enterprise-skills license activate <key>',
    );
    log(`license gate: paused ${moved.length} skill render(s) into ${quarantineDir()}`);
  } catch (e) {
    log(`license gate enforce error: ${e}`);
  }
}

/**
 * RESTORE: exact inverse of enforce, per the marker. Never overwrites — if a
 * skill was re-rendered while paused, the quarantined copy is left in place.
 * Quarantine dirs are only removed when empty (rmdirSync, non-recursive).
 */
function restoreQuarantined() {
  const marker = readJson(markerFile());
  if (!marker || !Array.isArray(marker.entries) || marker.entries.length === 0) return false;

  let restored = 0;
  for (const entry of marker.entries) {
    try {
      if (typeof entry?.from !== 'string' || typeof entry?.to !== 'string') continue;
      if (!existsSync(entry.to)) continue; // quarantined copy gone
      if (existsSync(entry.from)) continue; // re-rendered since — leave both
      moveEntry(entry.to, entry.from);
      restored++;
    } catch (e) {
      log(`license gate: restore failed for ${entry?.to}: ${e}`);
    }
  }
  try {
    rmSync(markerFile());
  } catch {
    /* ignore */
  }
  try {
    rmdirSync(join(quarantineDir(), 'skills'));
  } catch {
    /* non-empty or missing — leave it */
  }
  try {
    rmdirSync(quarantineDir());
  } catch {
    /* non-empty or missing — leave it */
  }
  return restored > 0;
}

function restoreSkills() {
  const restored = restoreQuarantined();
  if (!restored) return;
  // Re-sync so anything that drifted while paused is refreshed (best-effort).
  try {
    spawnSync('enterprise-skills', ['sync'], {
      cwd,
      shell: process.platform === 'win32',
      stdio: 'ignore',
      timeout: 60_000,
    });
  } catch {
    /* ignore */
  }
  console.log('License revalidated — skills restored');
  log('license gate: quarantined skills restored');
}

async function runLicenseGate() {
  try {
    if (!HOME_DIR) return;
    const license = readJson(LICENSE_FILE);
    // No license or free tier -> nothing to gate.
    if (!license || typeof license.key !== 'string' || !license.tier || license.tier === 'free') return;

    const now = Date.now();
    const lastValidatedIso = license.last_validated_at ?? license.activated_at;
    const lastValidated = Date.parse(lastValidatedIso ?? '');
    const fresh =
      Number.isFinite(lastValidated) && now - lastValidated < REVALIDATE_AFTER_HOURS * 3_600_000;

    if (fresh) {
      // Instant restore: a fresh validation (e.g. `license activate` just ran)
      // means the server said yes within 24h — undo any earlier pause.
      if (existsSync(markerFile())) restoreSkills();
      return;
    }

    // Revalidate: POST {key, device} with a 5s timeout.
    let outcome = 'network_error';
    let errorCode;
    // Hoisted past the fetch try: the accept path below persists the server's
    // truth from it, and a block-scoped const would be out of reach there.
    let serverData = null;
    try {
      const res = await fetch(VALIDATE_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          key: license.key,
          device: { id: license.device_id, hostname: hostname(), platform: process.platform },
        }),
        signal: AbortSignal.timeout(5000),
      });
      serverData = await res.json().catch(() => null);
      if (serverData && serverData.valid === true) {
        outcome = 'valid';
      } else if (serverData && serverData.valid === false) {
        outcome = 'invalid';
        errorCode = serverData.error_code;
      }
    } catch {
      /* network failure / timeout -> offline grace path */
    }

    // Decision mirror of license-gate.ts decideGateAction().
    if (outcome === 'valid') {
      try {
        const current = readJson(LICENSE_FILE);
        if (current && current.key === license.key && serverData) {
          // Mirror of license-gate.ts applyValidResponse() (itself matching
          // core's repairedLicenseRecord): persist the server's truth, not
          // just the timestamp — org policy must reach healthy caches through
          // this 24h path, not only via sync/bundle. Identity fields (key,
          // device_id, activated_at, telemetry opt-out) never come from the
          // response. Defensive types only — never trust the raw shape.
          if (
            typeof serverData.tier === 'string' &&
            ['free', 'pro', 'team', 'enterprise'].includes(serverData.tier)
          ) {
            current.tier = serverData.tier;
          }
          if (typeof serverData.email === 'string') current.email = serverData.email;
          if (typeof serverData.expires_at === 'string') current.expires_at = serverData.expires_at;
          if (Number.isInteger(serverData.seats)) current.seats = serverData.seats;
          if (
            serverData.entitlements &&
            typeof serverData.entitlements === 'object' &&
            !Array.isArray(serverData.entitlements)
          ) {
            current.entitlements = serverData.entitlements;
          }
          current.last_validated_at = new Date().toISOString();
          writeFileSync(LICENSE_FILE, `${JSON.stringify(current, null, 2)}`);
        }
      } catch {
        /* ignore */
      }
      if (existsSync(markerFile())) restoreSkills();
      return;
    }

    if (outcome === 'invalid' && (errorCode === 'KEY_INVALID' || errorCode === 'KEY_EXPIRED')) {
      // Explicit server NO about the key -> enforce now.
      enforceLicenseGate();
      return;
    }

    // Offline grace (network failure, or non-explicit invalid such as a seat
    // conflict). Unknown timestamp counts as day 0 — never enforce on unknown.
    const days = Number.isFinite(lastValidated) ? Math.floor((now - lastValidated) / 86_400_000) : 0;
    if (days >= ENFORCE_AFTER_DAYS) {
      enforceLicenseGate();
    } else if (days >= WARN_AFTER_DAYS) {
      console.log(
        `Couldn't verify your Enterprise Skills license for ${days} days — skills will pause after ${ENFORCE_AFTER_DAYS} days offline.`,
      );
    }
  } catch (e) {
    log(`license gate error: ${e}`);
  }
}

// ---------------------------------------------------------------------------
// Telemetry flush (inline mirror of cli/src/telemetry.ts flushTelemetry and
// cli/src/flush-journal.ts — keep the claim protocol in sync there, and the
// gate logic in sync with core/src/license.ts: isTelemetryOptedOut +
// effectiveTelemetryLevel, min(org, local) per LEARNING_LOOP_DESIGN D-2).
// This is an EGRESS point, so it applies the same composed-level filter the
// CLI flush does: a dumb forwarder here would ship queue residue the policy
// no longer allows.
// ---------------------------------------------------------------------------

// Mirror of core TELEMETRY_OPT_OUT_VALUES: the union of every spelling that
// ever shipped ("0" validate path, "off" event queue, "false" the guess).
const TELEMETRY_OPT_OUT_VALUES = new Set(['0', 'off', 'false']);
// Failure-shaped event types that still cross at level `error` (D-1). Keep in
// sync with core ERROR_LEVEL_EVENT_TYPES; unknown types need `all`.
const ERROR_LEVEL_EVENT_TYPES = new Set(['failure_class', 'user_correction', 'skill_failed']);
const LEVEL_RANK = { off: 0, error: 1, all: 2 };

function effectiveTelemetryLevel(license) {
  const envValue = (process.env.ENTERPRISE_SKILLS_TELEMETRY ?? '').trim().toLowerCase();
  const optedOut = envValue.length > 0
    ? TELEMETRY_OPT_OUT_VALUES.has(envValue)
    : license?.telemetry === false;
  const localLevel = optedOut ? 'off' : 'all';
  // No record = no org; with a record, the delivered level or the D-1
  // default `error` — exactly what the server answers for an untouched org.
  const orgRaw = license?.entitlements?.org_policy?.telemetry_level;
  const orgLevel = !license ? 'all' : (orgRaw === 'all' || orgRaw === 'off' ? orgRaw : 'error');
  return LEVEL_RANK[orgLevel] <= LEVEL_RANK[localLevel] ? orgLevel : localLevel;
}

// Mirror of flush-journal.ts CLAIM_PATTERN / ORPHAN_AGE_MS / HARD_ORPHAN_AGE_MS
// / QUEUE_CAP / FLUSH_LOCK_BASENAME / LOCK_STALE_MS.
const CLAIM_PATTERN = /^\.telemetry-journal\.\d+-\d+\.flushing$/;
const ORPHAN_AGE_MS = 15 * 60_000;
const HARD_ORPHAN_AGE_MS = 60 * 60_000;
const QUEUE_CAP = 200;
const LOCK_FILE = join(ES_DIR, '.telemetry-journal.flush-lock');
const LOCK_STALE_MS = 2 * 60_000;

// Mirror of flush-journal.ts acquireFlushLock/verifyFlushLock/releaseFlushLock:
// exclusive-create ('wx' → CREATE_NEW, kernel-atomic on Windows and POSIX) is
// the fencing primitive; the token is read back because a stale-lock takeover
// unlinks by PATH — whoever's token is in the file owns the lock.
function isStaleLock(content, mtimeMs, now) {
  const m = /^\d+-(\d+)-/.exec(content.trim());
  const born = m ? Number(m[1]) : NaN;
  return now - (Number.isFinite(born) ? born : mtimeMs) > LOCK_STALE_MS;
}

function verifyFlushLock(token) {
  try {
    return readFileSync(LOCK_FILE, 'utf8').trim() === token;
  } catch {
    return false;
  }
}

function acquireFlushLock() {
  const now = Date.now();
  const token = `${process.pid}-${now}-${randomUUID().slice(0, 8)}`;
  mkdirSync(ES_DIR, { recursive: true });
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      writeFileSync(LOCK_FILE, token, { flag: 'wx' });
      return verifyFlushLock(token) ? token : null;
    } catch {
      /* exists — staleness check below */
    }
    let content;
    let mtimeMs;
    try {
      content = readFileSync(LOCK_FILE, 'utf8');
      mtimeMs = statSync(LOCK_FILE).mtimeMs;
    } catch {
      continue; // vanished — retry the create
    }
    if (!isStaleLock(content, mtimeMs, now)) return null; // live flusher
    try {
      // Re-read immediately before the unlink: only a STILL-stale lock may die.
      if (!isStaleLock(readFileSync(LOCK_FILE, 'utf8'), statSync(LOCK_FILE).mtimeMs, Date.now())) return null;
      rmSync(LOCK_FILE, { force: true });
    } catch {
      return null;
    }
    // Loop: the exclusive create re-arbitrates among concurrent takeovers.
  }
  return null;
}

function releaseFlushLock(token) {
  try {
    if (readFileSync(LOCK_FILE, 'utf8').trim() !== token) return; // not ours anymore
  } catch {
    return;
  }
  try {
    rmSync(LOCK_FILE, { force: true });
  } catch {
    /* held open — a future takeover ages it out */
  }
}

// Mirror of flush-journal.ts isPidAlive: liveness veto for the orphan sweep.
function isPidAlive(pid) {
  if (!Number.isFinite(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    return err && err.code === 'EPERM';
  }
}

// Mirror of flush-journal.ts parseJournalLines: a torn LINE is skippable
// damage — parse what parses, keep the file.
function parseJournalLines(text) {
  const events = [];
  for (const line of text.split(/\r?\n/)) {
    if (!line.trim()) continue;
    try {
      const parsed = JSON.parse(line);
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) events.push(parsed);
    } catch {
      /* torn or corrupt line — skip it */
    }
  }
  return events;
}

// Mirror of flush-journal.ts appendJournalEvents: one O_APPEND write, never
// read-modify-write.
function appendJournalEvents(events) {
  if (events.length === 0) return;
  mkdirSync(ES_DIR, { recursive: true });
  appendFileSync(JOURNAL_FILE, events.map((e) => JSON.stringify(e)).join('\n') + '\n');
}

async function flushTelemetryQueue() {
  // The FENCE (mirror of cli doFlushTelemetry): exactly one flusher per HOME
  // at a time. Losing the exclusive create means another flusher is live —
  // skip the cycle, the events keep queueing (C-2). Everything below,
  // including recovery, runs under this lock.
  const lockTokenHeld = acquireFlushLock();
  if (lockTokenHeld === null) return;
  try {
    // D-4: drain a v1 array file left by old writers — append into the
    // journal (fresh event_id where absent, so the server dedup absorbs a
    // concurrent double-drain), then delete. A v1 file that does not parse is
    // left alone: a live v1 writer will overwrite it with a valid array.
    try {
      const v1 = JSON.parse(readFileSync(QUEUE_FILE, 'utf8'));
      if (Array.isArray(v1)) {
        appendJournalEvents(
          v1.filter((e) => e && typeof e === 'object').map((e) => ({ event_id: randomUUID(), ...e })),
        );
        rmSync(QUEUE_FILE, { force: true });
      }
    } catch {
      /* missing, torn, or corrupt — leave it */
    }

    // Orphan sweep (under the lock, so it can never race a live flusher's
    // claim/release): a claim older than 15 minutes whose OWNER PROCESS IS
    // GONE is a crashed flusher — its events go back to the live journal
    // (append BEFORE remove: a crash in between duplicates, never loses),
    // loudly, never deleted unsent. A live owner keeps its segment until the
    // hard pid-recycling bound passes.
    try {
      const now = Date.now();
      for (const name of readdirSync(ES_DIR)) {
        if (!CLAIM_PATTERN.test(name)) continue;
        try {
          const full = join(ES_DIR, name);
          const m = /^\.telemetry-journal\.(\d+)-(\d+)\.flushing$/.exec(name);
          const ownerPid = m ? Number(m[1]) : NaN;
          const born = m && Number.isFinite(Number(m[2])) ? Number(m[2]) : statSync(full).mtimeMs;
          if (now - born <= ORPHAN_AGE_MS) continue;
          if (isPidAlive(ownerPid) && now - born <= HARD_ORPHAN_AGE_MS) continue;
          const events = parseJournalLines(readFileSync(full, 'utf8'));
          appendJournalEvents(events);
          rmSync(full, { force: true });
          log(`telemetry: recovered ${events.length} event(s) from orphaned claim ${name}`);
        } catch {
          /* recover on a later cycle — nothing deleted unsent */
        }
      }
    } catch {
      /* no directory yet — nothing to sweep */
    }

    // The claim: move the journal aside for exclusive draining. The token is
    // re-verified immediately before the rename so the rename only ever runs
    // under mutual exclusion — rename is a data move here, never the fence
    // (a successful Windows rename is NOT proof of exclusivity).
    if (!verifyFlushLock(lockTokenHeld)) return;
    const claimed = join(ES_DIR, `.telemetry-journal.${process.pid}-${Date.now()}.flushing`);
    try {
      renameSync(JOURNAL_FILE, claimed);
    } catch {
      return;
    }
    // Backstop for VERSION SKEW: an old (4.30.x) flusher renames without the
    // lock, which re-opens the concurrent-rename anomaly against us. Confirm
    // we actually hold the file; the loser simply does not flush this cycle
    // (its events are in the other flusher's claim).
    try {
      statSync(claimed);
    } catch {
      return;
    }

    let consumed = 0;
    let unsent = [];
    try {
      const all = parseJournalLines(readFileSync(claimed, 'utf8'));
      consumed = all.length;
      // The 200 cap, enforced at claim time (§3.3): oldest dropped, loudly.
      const kept = all.length > QUEUE_CAP ? all.slice(all.length - QUEUE_CAP) : all;
      if (kept.length < all.length) log(`telemetry: queue over cap — dropped ${all.length - kept.length} oldest event(s)`);

      const license = readJson(LICENSE_FILE);
      const level = effectiveTelemetryLevel(license);
      // Same drop-at-egress rule as the CLI flush: events the composed policy
      // forbids are removed, not held for a friendlier policy later.
      unsent = kept.filter(
        (e) =>
          LEVEL_RANK[level] >=
          LEVEL_RANK[ERROR_LEVEL_EVENT_TYPES.has(e?.event_type) ? 'error' : 'all'],
      );

      if (license && typeof license.key === 'string' && unsent.length > 0) {
        const ring = license?.entitlements?.org_policy?.update_ring === 'canary' ? 'canary' : 'stable';
        // The claim is exclusive — drain it fully, batches of 50, until empty
        // or the first failure. What cannot cross goes back below.
        while (unsent.length > 0) {
          try {
            const res = await fetch(TELEMETRY_URL, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                license_key: license.key,
                events: unsent.slice(0, 50).map((e) => ({
                  ...e,
                  metadata: { ...(e && typeof e.metadata === 'object' ? e.metadata : {}), ring },
                })),
              }),
              signal: AbortSignal.timeout(5000),
            });
            if (!res.ok) break;
            unsent = unsent.slice(50);
          } catch {
            break; // network failure is fine — the remainder goes back
          }
        }
      }
    } finally {
      // D-3: recovery APPENDS to the live journal, never overwrites. Restore
      // BEFORE releasing the claim: a crash in between duplicates (absorbed
      // by the server's event_id dedup) rather than loses. If any restore
      // fails, the claim is LEFT STANDING for the orphan sweep — unlinking it
      // would destroy the only copy of what could not be re-appended.
      let restored = true;
      try {
        appendJournalEvents(unsent);
      } catch {
        restored = false; // the claim file still holds them; the sweep recovers
      }
      if (restored) {
        // Release: re-check for lines a racing appender landed after our read
        // (POSIX pre-rename fd window), append the surplus back, then unlink
        // ONLY if the surplus was saved. A refused unlink leaves the claim
        // for the sweep.
        try {
          const events = parseJournalLines(readFileSync(claimed, 'utf8'));
          if (events.length > consumed) appendJournalEvents(events.slice(consumed));
          try {
            rmSync(claimed, { force: true });
          } catch {
            /* held open — the sweep will finish the job */
          }
        } catch {
          /* unreadable or restore refused — never unlink what we could not save */
        }
      }
    }
  } catch {
    /* silent failure — events stay journaled */
  } finally {
    releaseFlushLock(lockTokenHeld);
  }
}

// ---------------------------------------------------------------------------
// Orchestration session init (original hook behavior)
// ---------------------------------------------------------------------------

function runOrchestrationInit() {
  if (!existsSync(configPath)) {
    return;
  }

  let config = {};
  try {
    config = JSON.parse(readFileSync(configPath, 'utf8'));
  } catch (e) {
    log(`invalid orchestration-hooks.json: ${e}`);
    return;
  }

  if (!config.sessionStartInit) {
    return;
  }

  if (existsSync(sessionPath)) {
    log('session file already present; skip init');
    return;
  }

  const isWin = process.platform === 'win32';
  const result = spawnSync('enterprise-skills', ['orchestrate', 'init'], {
    cwd,
    encoding: 'utf8',
    shell: isWin,
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  if (result.error) {
    log(`spawn error: ${result.error.message}`);
    return;
  }

  if (result.status !== 0) {
    log(`orchestrate init exit ${result.status}: ${(result.stderr || result.stdout || '').slice(0, 500)}`);
  }
}

// Agent brief at session start: carry over pending signals and an active
// workflow's ready steps into the new session's context (stdout is injected
// by IDEs that support it; _agent-brief.md persists it either way).
function emitAgentBrief() {
  if (!existsSync(configPath)) {
    return;
  }
  let config = {};
  try {
    config = JSON.parse(readFileSync(configPath, 'utf8'));
  } catch {
    return;
  }
  if (!config.sessionStartInit || config.agentBrief === false) {
    return;
  }

  const isWin = process.platform === 'win32';
  const result = spawnSync('enterprise-skills', ['orchestrate', 'brief'], {
    cwd,
    encoding: 'utf8',
    shell: isWin,
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  if (result.error) {
    log(`brief spawn error: ${result.error.message}`);
    return;
  }
  if (result.status === 0 && (result.stdout || '').trim()) {
    console.log(result.stdout.trim());
  } else if (result.status !== 0) {
    log(`brief exit ${result.status}: ${(result.stderr || '').slice(0, 300)}`);
  }
}

// ---------------------------------------------------------------------------
// Update notice (ADR 0001) — surface the last cached update plan, offline.
// ---------------------------------------------------------------------------

function emitUpdateNotice() {
  try {
    const cache = readJson(UPDATE_CACHE_FILE);
    if (!cache) return;
    if (cache.counts && cache.counts.total > 0 && typeof cache.summary === 'string' && cache.summary) {
      console.log(`⬆ Enterprise Skills: ${cache.summary}`);
    }
    // Model-conditioning staleness (ADR 0001 freshness signal) — surfaced from the
    // same offline cache. Actionable only: printed when a profile is past threshold.
    const stale = cache.conditioning && Array.isArray(cache.conditioning.stale) ? cache.conditioning.stale : [];
    if (stale.length > 0) {
      const names = stale.map((s) => s.display).filter(Boolean).join(', ');
      console.log(`⬆ Enterprise Skills: model conditioning may be stale for ${names} — run: enterprise-skills update check`);
    }
  } catch {
    /* ignore — a missing/corrupt cache must never affect session start */
  }
}

// Auto-B (model-conditioning precedence): in Claude Code / CLI the active model is
// observable, so refresh the Tier-2 file every session — it can never go stale. In
// declared-model IDEs (Cursor/Copilot/Windsurf/JetBrains) the model is NOT observable,
// so we do not auto-write here; those stay on-demand (hybrid) per the precedence rule.
function looksLikeClaudeOrCli() {
  const e = process.env;
  return !!(e.CLAUDE_CODE || e.ANTHROPIC_CLI || e.CI || e.GITHUB_ACTIONS);
}

function writeActiveConditioning() {
  try {
    if (!looksLikeClaudeOrCli()) return;
    const out = join(cwd, '.project-ai', 'model-conditioning.active.md');
    const result = spawnSync(
      'enterprise-skills',
      ['autopilot', 'conditioning', '--write', out],
      { cwd, shell: process.platform === 'win32', stdio: 'ignore', timeout: 30_000 },
    );
    if (result.error) log(`conditioning write error: ${result.error.message}`);
  } catch (e) {
    log(`conditioning write error: ${e}`);
  }
}

drainStdin();
await runLicenseGate();
await flushTelemetryQueue();
emitUpdateNotice();
writeActiveConditioning();
runOrchestrationInit();
emitAgentBrief();
process.exit(0);
